// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemSAKZ8Y6ZgBODSNw_CLHd6pJZq8kqgg',
    appId: '1:1002931834957:web:23e975b0e12ff567610c04',
    messagingSenderId: '1002931834957',
    projectId: 'endprojectdashbordmanager',
    authDomain: 'endprojectdashbordmanager.firebaseapp.com',
    storageBucket: 'endprojectdashbordmanager.appspot.com',
    measurementId: 'G-ZVDB22N4X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqLotgTs540sqU4NjhJlYRiLX4n70DOCM',
    appId: '1:1002931834957:android:690858c2db578848610c04',
    messagingSenderId: '1002931834957',
    projectId: 'endprojectdashbordmanager',
    storageBucket: 'endprojectdashbordmanager.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemSAKZ8Y6ZgBODSNw_CLHd6pJZq8kqgg',
    appId: '1:1002931834957:web:27cf1e03b681b725610c04',
    messagingSenderId: '1002931834957',
    projectId: 'endprojectdashbordmanager',
    authDomain: 'endprojectdashbordmanager.firebaseapp.com',
    storageBucket: 'endprojectdashbordmanager.appspot.com',
    measurementId: 'G-BWMK2C00FC',
  );
}
